version: '3.8'

services:
  gateway:
    build:
      context: ./gateway/backend
      dockerfile: Dockerfile
    container_name: edubrain-gateway
    ports:
      - "5000:5000"
    volumes:
      - ./gateway/frontend:/frontend
    environment:
      - PORT=5000
      - AUTH_SERVICE_URL=http://auth:5001
      - STUDENTS_SERVICE_URL=http://students:5002
      - COURSES_SERVICE_URL=http://courses:5003
      - ENROLLMENTS_SERVICE_URL=http://enrollments:5004
      - ATTENDANCE_SERVICE_URL=http://attendance:5005
      - ARTICLES_SERVICE_URL=http://articles:5006
      - FORM_DISCUSSION_SERVICE_URL=http://form_discussion:5007
    depends_on:
      - auth
      - students
      - courses
      - enrollments
      - attendance
      - articles
      - form_discussion

  auth:
    build:
      context: ./auth/backend
      dockerfile: Dockerfile
    container_name: edubrain-auth
    volumes:
      - ./auth/frontend:/frontend
    environment:
      - AUTH_PORT=5001
      - STUDENTS_SERVICE_URL=http://students:5002/graphql

  students:
    build:
      context: ./students/backend
      dockerfile: Dockerfile
    container_name: edubrain-students
    volumes:
      - ./students/frontend:/frontend
    environment:
      - STUDENT_PORT=5002

  courses:
    build:
      context: ./courses/backend
      dockerfile: Dockerfile
    container_name: edubrain-courses
    volumes:
      - ./courses/frontend:/frontend
    environment:
      - COURSE_PORT=5003
      - ARTICLES_SERVICE_URL=http://articles:5006/graphql

  enrollments:
    build:
      context: ./enrollments/backend
      dockerfile: Dockerfile
    container_name: edubrain-enrollments
    volumes:
      - ./enrollments/frontend:/frontend
    environment:
      - ENROLLMENT_PORT=5004
      - STUDENTS_SERVICE_URL=http://students:5002/graphql
      - COURSES_SERVICE_URL=http://courses:5003/graphql
      - ATTENDANCE_SERVICE_URL=http://attendance:5005/graphql
      - ARTICLES_SERVICE_URL=http://articles:5006/graphql

  attendance:
    build:
      context: ./attendance/backend
      dockerfile: Dockerfile
    container_name: edubrain-attendance
    volumes:
      - ./attendance/frontend:/frontend
    environment:
      - ATTENDANCE_PORT=5005
      - STUDENTS_SERVICE_URL=http://students:5002/graphql
      - COURSES_SERVICE_URL=http://courses:5003/graphql
      - ARTICLES_SERVICE_URL=http://articles:5006/graphql

  articles:
    build:
      context: ./articles/backend
      dockerfile: Dockerfile
    container_name: edubrain-articles
    volumes:
      - ./articles/frontend:/frontend
    environment:
      - ARTICLE_PORT=5006
      - ENROLLMENTS_SERVICE_URL=http://enrollments:5004/graphql

  form_discussion:
    build:
      context: ./form_discussion/backend
      dockerfile: Dockerfile
    container_name: edubrain-form-discussion
    volumes:
      - ./form_discussion/frontend:/frontend
    environment:
      - PORT=5007
